package ExceptionHandling;

public class Testing {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		int a[]=new int[3];
		try {
		a[3]=10; //AIOE--Runtime Exception
		}
		catch(ArrayIndexOutOfBoundsException e)
		{
			
		}
		
		//business logic--implement 10 lines code 
		System.out.println("Bye");
		///try-catch
		
		//try--catch
	}

}
